// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/nation/barChart.vue')['default']
    BarChart1: typeof import('./src/components/nation/barChart1.vue')['default']
    CardItem: typeof import('./src/components/cardItem.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    IndexHeader: typeof import('./src/components/indexHeader.vue')['default']
    LineChart: typeof import('./src/components/nation/lineChart.vue')['default']
    ListItem: typeof import('./src/components/listItem.vue')['default']
    MainHeader: typeof import('./src/components/mainHeader.vue')['default']
    Map: typeof import('./src/components/nation/map.vue')['default']
    NavBox: typeof import('./src/components/nation/navBox.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NTree: typeof import('naive-ui')['NTree']
    PieChart: typeof import('./src/components/nation/pieChart.vue')['default']
    RadarChart: typeof import('./src/components/nation/radarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipBus: typeof import('./src/components/nation/tooltipBus.vue')['default']
  }
}
